# python summary

string methods
- manipulations (string is immutable!):
    - `s.strip()`
    - `s.lower()`
    - `s.join([s1, s2])` (s as separator)
    - `s.replace(old, new)`
- lookup first occurance: 
        - `s.find(e)`  (-1 no result)
        - `if e in s: s.index(e)` (valueerror no result)
- lookup all occurance:
        - `s.count(e)`
- `for i in s`

list methods
- shallow copy: `L.copy()`, `L[:]`, `L[i:j]` (use deepcopy for nested list)
- mutation in place
    - `L.sort()`/`L.sort(reverse=True)` (DESC), `L.reverse()`
    - `L.pop()`, `L.pop(i)`, `L.remove(e)`(1st orruance)
    - `L.insert(i,e)`, `L.append(e)`, `L.extend(L1)`
- lookup first occurance
    - `if e in L: L.index(e)`
- lookup all occurance
    - `L.count(e)`
- `for idx, val in enumerate(L)`


dict methods
- property/lookup
    - `len(dict)`
    - `k in d` to check keys
- delete
    - `del dict[k]` or `dict.pop(k)`
- reassign value/add
    - `dict[k]=v`
- `for k, v in dict.items()`, `for k in dict.keys()`, `for v in dict.values()`, `for k in dict`

In [ ]:
# shallow copy only copies outer list
a = [[1, 2], [3, 4]]
b = a.copy()
b[0][0] = 99

print(a)  # [[99, 2], [3, 4]]

[[99, 2], [3, 4]]

### linked list Numpy Array, Pandas DataFrame
- Numpy
    - `b = a` or slicing link array
    - fancy indexing `a[[1, 3]]`, `a.copy()` for copies
- Pandas
    - `b = a`, slicing (`.iloc[,]`, `df['x']`, or `.loc[:, 'x']`) link DataFrame b/c they create a new view
    - filtering `df[df['x]>1]`, `.loc[]`, `.groupby(..)` unlink

In [ ]:
from IPython.display import display
import numpy as np; import pandas as pd
df1 = pd.DataFrame({"x": [1, 2], "y": [10, 20]})
df2 = df1      # same object

# create a filtered result
df3=df2.loc[df2['x']<2, ['x','y']]

# create a snapshot (i.e. view)
df4=df2.iloc[0, :]

# not linked
df4_2=df2.loc[:, ["x"]].rename(columns={"x": "X_new"})

# linked (changes only meta data)
df4_3 = (df2.loc[:, "x"])
df4_3.name = "X_df4"

# create a view
df5=df2.x

# create a filtered results
df6=df2['x'].unique()


df2.loc[0, "x"] = 999
display("df1:", df1)
display("df2:", df2)
display("df3:", df3) # not linked to 2
display("df4:", df4) # linked to 2
display("df4_2:", df4_2) # not linked to 2
display("df4_3:", df4_3) # linked to 2
display("df5:", df5) # linked to 2
display("df6:", df6) # not linked to 2

'df1:'

     x   y
0  999  10
1    2  20

'df2:'

     x   y
0  999  10
1    2  20

'df3:'

   x   y
0  1  10

'df4:'

x    999
y     10
Name: 0, dtype: int64

'df4_2:'

   X_new
0      1
1      2

'df4_3:'

0    999
1      2
Name: X_df4, dtype: int64

'df5:'

0    999
1      2
Name: X_df4, dtype: int64

'df6:'

array([1, 2])

In [ ]:
a = np.array([1, 2, 3])
b = a[a<3]  # filtered object
c = a[:2]   # create a new view
a[0] = 99
print("a:", a)  
print("b:", b)  # not linked
print("c:", c)  # linked

a: [99  2  3]
b: [1 2]
c: [99  2]

# Numpy summary

- attributes
    - `.size`: total elements
    - `.shape[0]`: # of rows
    - `np.nan`: checking `np.isnan(a)` or replacement `a.fillna(0)` or `a[np.isnan(a)]=0`
- creation
    - `np.arange(start, excl. end, gap)`
    - `np.zeros((# rows, # cols))` or `np.ones((m,n))`
- reshaping
    - `.reshape(m,n)`
- slicing maintaining 2D
    - `a[[-1],:]` or `a[:, 1].reshape(-1,1)`
- `for row in A:`, `for idx, row in enumerate(A)`, or `for col in A.T:`

2 matrices
- combining
    - adding rows: `np.concatenate((a, b), axis=0)`
    - adding columns: `np.concatenate((a, b), axis=1)` or `np.c_[a,b]` for shortcut